#!/usr/bin/env bash

origdir=$(pwd)
scriptdir=$(dirname $0)
args=()
for arg in $@; do
    args+=($(readlink -f $arg))
done

cd $scriptdir
stack exec latc_x86_64 ${args[@]}
ret=$?
cd $origdir
exit $ret
